In [1]:
import pandas as pd

enrolment = pd.read_csv(
    "../data/enrolment.csv",
    low_memory=False
)

print("Enrolment loaded")

Enrolment loaded

In [2]:
enrolment.shape
enrolment.head()

         date      state district  pincode  age_0_5  age_5_17  age_18_greater
0  31-12-2025  Karnataka    Bidar   585330        2         3               0
1  31-12-2025  Karnataka    Bidar   585402        6         0               0
2  31-12-2025  Karnataka    Bidar   585413        1         0               0
3  31-12-2025  Karnataka    Bidar   585418        1         2               0
4  31-12-2025  Karnataka    Bidar   585421        4         3               0

In [ ]:
demographic = pd.read_csv(
    "../data/demographic.csv",
    low_memory=False
)

print("Demographic loaded")

Demographic loaded

In [4]:
demographic.shape
demographic.head()

         date           state  district  pincode  demo_age_5_17  demo_age_17_
0  16-12-2025  Madhya Pradesh  Shajapur   465113              0             4
1  16-12-2025  Madhya Pradesh  Shajapur   465226              2            14
2  16-12-2025  Madhya Pradesh  Shajapur   465339              1             2
3  16-12-2025  Madhya Pradesh  Shajapur   465447              1            19
4  16-12-2025  Madhya Pradesh   Sheopur   476332             11            25

In [5]:
biometric = pd.read_csv(
    "../data/biometric.csv",
    low_memory=False
)

print("Biometric loaded")

Biometric loaded

In [6]:
biometric.shape
biometric.head()

,date,state,district,pincode,bio_age_5_17,bio_age_17_
0,08-12-2025,Uttar Pradesh,Moradabad,244411,4,2
1,08-12-2025,Uttar Pradesh,Moradabad,244601,14,19
2,08-12-2025,Uttar Pradesh,Muzaffarnagar,251002,22,37
3,08-12-2025,Uttar Pradesh,Muzaffarnagar,251202,4,4
4,08-12-2025,Uttar Pradesh,Muzaffarnagar,251319,4,7

In [7]:
enrolment['date'] = pd.to_datetime(enrolment['date'], dayfirst=True)
demographic['date'] = pd.to_datetime(demographic['date'], dayfirst=True)
biometric['date'] = pd.to_datetime(biometric['date'], dayfirst=True)

In [8]:
enrolment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6029 entries, 0 to 6028
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            6029 non-null   datetime64[ns]
 1   state           6029 non-null   object
 2   district        6029 non-null   object
 3   pincode         6029 non-null   int64
 4   age_0_5         6029 non-null   int64
 5   age_5_17        6029 non-null   int64
 6   age_18_greater  6029 non-null   int64
dtypes: datetime64[ns](1), int64(4), object(2)
memory usage: 329.8+ KB

In [9]:
for df in [enrolment, demographic, biometric]:
    df['year'] = df['date'].dt.year
    df['month'] = df['date'].dt.month

In [10]:
enrolment[['date', 'year', 'month']].head()

        date  year  month
0 2025-12-31  2025     12
1 2025-12-31  2025     12
2 2025-12-31  2025     12
3 2025-12-31  2025     12
4 2025-12-31  2025     12

In [11]:
enrolment.isna().sum()
demographic.isna().sum()
biometric.isna().sum()

date            0
state           0
district        0
pincode         0
bio_age_5_17    0
bio_age_17_     0
year            0
month           0
dtype: int64

In [12]:
enrolment.to_csv("../data/enrolment_cleaned.csv", index=False)
demographic.to_csv("../data/demographic_cleaned.csv", index=False)
biometric.to_csv("../data/biometric_cleaned.csv", index=False)